### ISSUE TITLE
Issues with MLFlow 2.0

### ISSUE THREAD

**Issue by gvelimir** [ArrichM/dynaflow#2]
The latest version of MLFlow 2.0 does not function with Dynaflow. Since MLFlow removed the list_experiments method, the tables from the backend store could not be fetched. Here is the stack trace:

2022/11/17 07:42:02 ERROR mlflow.server: Exception on /ajax-api/2.0/mlflow/experiments/search [GET]
Traceback (most recent call last):
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/mlflow/server/handlers.py", line 452, in wrapper
    return func(*args, **kwargs)
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/mlflow/server/handlers.py", line 522, in wrapper
    return func(*args, **kwargs)
  File "/home/velimir/anaconda3/envs/intertec-mlops/lib/python3.10/site-packages/mlflow/server/handlers.py", line 1017, in _search_experiments
    response_message.experiments.extend([e.to_proto() for e in experiment_entities])
TypeError: 'NoneType' object is not iterable

**Comment by BenWilson2** [comment]
Hi @ArrichM great package, by the way! When in the process of updating for MLflow2.0, note that we added a top-level attribute to `Run` wherein we include `run_name` (as well as preserve the tag-based `tags.mlflow.runName` convention for backwards compatibility). 
Feel free to reach out to the team on the MLflow slack with any other questions you might have around breaking changes in 2.0 :)
